package site.neworld.cio.unsafe

@JvmInline
@OptIn(ExperimentalUnsignedTypes::class)
value class AlignedAccess(private val access: UnsafeAccess) {
    fun getByteArray(offset: Int, size: Int) = access.getByteArray(offset, size)
    fun getUByteArray(offset: Int, size: Int) = access.getUByteArray(offset, size)
    fun getShortArray(offset: Int, size: Int) = access.getShortArray(offset, size, false)
    fun getUShortArray(offset: Int, size: Int) = access.getUShortArray(offset, size, false)
    fun getIntArray(offset: Int, size: Int) = access.getIntArray(offset, size, false)
    fun getUIntArray(offset: Int, size: Int) = access.getUIntArray(offset, size, false)
    fun getLongArray(offset: Int, size: Int) = access.getLongArray(offset, size, false)
    fun getULongArray(offset: Int, size: Int) = access.getULongArray(offset, size, false)
    fun getFloatArray(offset: Int, size: Int) = access.getFloatArray(offset, size, false)
    fun getDoubleArray(offset: Int, size: Int) = access.getDoubleArray(offset, size, false)

    fun putByteArray(v: ByteArray, offset: Int) = access.putByteArray(v, offset)
    fun putUByteArray(v: UByteArray, offset: Int) = access.putUByteArray(v, offset)
    fun putShortArray(v: ShortArray, offset: Int) = access.putShortArray(v, offset, false)
    fun putUShortArray(v: UShortArray, offset: Int) = access.putUShortArray(v, offset, false)
    fun putIntArray(v: IntArray, offset: Int) = access.putIntArray(v, offset, false)
    fun putUIntArray(v: UIntArray, offset: Int) = access.putUIntArray(v, offset, false)
    fun putLongArray(v: LongArray, offset: Int) = access.putLongArray(v, offset, false)
    fun putULongArray(v: ULongArray, offset: Int) = access.putULongArray(v, offset, false)
    fun putFloatArray(v: FloatArray, offset: Int) = access.putFloatArray(v, offset, false)
    fun putDoubleArray(v: DoubleArray, offset: Int) = access.putDoubleArray(v, offset, false)

    fun getByte(offset: Int) = access.getByte(offset)
    fun getUByte(offset: Int) = access.getByte(offset).toUByte()
    fun getShort(offset: Int) = access.getShort(offset)
    fun getUShort(offset: Int) = access.getShort(offset).toUShort()
    fun getInt(offset: Int) = access.getInt(offset)
    fun getUInt(offset: Int) = access.getInt(offset).toUInt()
    fun getLong(offset: Int) = access.getLong(offset)
    fun getULong(offset: Int) = access.getLong(offset).toULong()
    fun getFloat(offset: Int) = access.getFloat(offset)
    fun getDouble(offset: Int) = access.getDouble(offset)

    fun putByte(offset: Int, v: Byte) = access.putByte(offset, v)
    fun putUByte(offset: Int, v: UByte) = access.putByte(offset, v.toByte())
    fun putShort(offset: Int, v: Short) = access.putShort(offset, v)
    fun putUShort(offset: Int, v: UShort) = access.putShort(offset, v.toShort())
    fun putInt(offset: Int, v: Int) = access.putInt(offset, v)
    fun putUInt(offset: Int, v: UInt) = access.putInt(offset, v.toInt())
    fun putLong(offset: Int, v: Long) = access.putLong(offset, v)
    fun putULong(offset: Int, v: ULong) = access.putLong(offset, v.toLong())
    fun putFloat(offset: Int, v: Float) = access.putFloat(offset, v)
    fun putDouble(offset: Int, v: Double) = access.putDouble(offset, v)
}